- name: "Install powerline"
  pip:
    executable: pip3
    name: powerline-status
  tags:
    - dotfiles

- name: "Install parellel"
  apt:
    name: parallel
  become: True

- name: "Ensure all basefolders are created"
  file:
    dest: "{{ item.dest | dirname }}"
    state: directory
  with_items: "{{ links }}"
  tags:
    - dotfiles

- name: "Ensure all symlinks are placed"
  file:
    src: "{{ playbook_dir }}/roles/dotfiles/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items: "{{ links }}"
  tags:
    - dotfiles