- name: "Install powerline"
  pip:
    executable: pip3
    name: powerline-status
  tags:
    - dotfiles

- name: "Install parellel"
  apt:
    name: parallel
  become: True

- name: "Ensure all basefolders are created"
  file:
    dest: "{{ ansible_env.HOME }}/{{ item.dest | dirname }}"
    state: directory
  with_items: "{{ links }}"
  tags:
    - dotfiles

- name: "Ensure all symlinks are placed"
  file:
    src: "{{dotfiles_location}}/files/{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    state: link
  with_items: "{{ links }}"
  tags:
    - dotfiles
